# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

# Site settings
url: "https://www.sustainableaihub.org"
title: "Sustainable AI Hub"
description: "The Sustainable AI Hub aims to bring together resources, projects and materials around making AI more sustainable."
permalink: pretty
logo: "https://github.com/SustainableAIHub/sustainableaihub.github.io/blob/main/assets/logo.png?raw=true"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Resources
    url: /resources/
  - title: Sign up
    url: /sign-up/

# Footer nav
navigation_footer:
  - title: Back to top
    url: "#top"

# Collections
collections:
  posts:
    title: Resources
    output: true
    description: "Sustainable AI Resources"
    aside: true
    feature_image: "https://github.com/SustainableAIHub/sustainableaihub.github.io/blob/main/assets/DistortedDandelions.png?raw=true"

# Collection settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap
