# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

# Site settings
url: "https://www.sustainableaihub.org"
title: "Sustainable AI Hub"
description: "The Sustainable AI Hub aims to bring together resources, projects and materials around making AI more sustainable."
permalink: pretty
logo: "assets/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Resources
    url: /resources/
  - title: Sign up for updates
    url: /sign-up/

# Footer nav
navigation_footer:
  - title: Back to top
    url: "#top"

# Collections
collections:
  posts:
    title: Resources
    output: true
    description: "Sustainable AI Resources"
    feature_text: |
      Sustainable AI Resources
    feature_image: "https://github.com/SustainableAIHub/sustainableaihub.github.io/blob/main/assets/DistortedDandelions.png?raw=true"

# Collection settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
